name: Petstore_Pipeline

on:
  push:
    branches:    
      - '*'         
      - '*/*'       
      - '**'        
      - '!dev'   
      - '!qut'   
      - '!main'  
      - 'master'      
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Petstore
        working-directory: ./petstore
        run: mvn clean install -DuseGitHubPackages=true deploy -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Petstore Docker image
        working-directory: ./petstore
        run: | 
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
