name: Petstore_Pipeline

on:
  push:
    branches:    
      - '*'         
      - '*/*'       
      - '**'        
      - '!dev'   
      - '!qut'   
      - '!main'   

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Petstore
        working-directory: ./petstore
        run: mvn clean install -DuseGitHubPackages=true deploy -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Petstore docker image
        id: build-image
        working-directory: ./petstore
        run: docker build . -t petstore
      - name: Tag Petstore docker image
        working-directory: ./petstore
        run: docker tag petstore ghcr.io/ereingold/petstore
      - name: Push Petstore docker image
        working-directory: ./petstore
        run: docker push ghcr.io/ereingold/petstore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
