name: Petstore_Pipeline

on:
  push:
    branches:    
      - '*'         
      - '*/*'       
      - '**'        
      - '!dev'   
      - '!qut'   
      - '!main'   
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Petstore
        working-directory: ./petstore
        run: mvn clean install -DuseGitHubPackages=true deploy -P github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build DHIR docker image
        id: build-image
        working-directory: ./petstore
        run: docker build . -t petstore
      - name: Tag DHIR docker image
        working-directory: ./petstore
        run: docker tag petstore ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Push DHIR docker image
        working-directory: ./petstore
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
